### ISSUE TITLE
Add Merge sort Algorithm in cpp

### ISSUE THREAD

**Issue by bosedipayan** [NamanBohra6301/DSA#10]
Hi @NamanBohra6301, I want to add this algorithm using C++. 
Could you please assign this to me?

**Comment by NamanBohra6301** [comment]
Go forward with it

**Comment by pallavi2031** [comment]
can you assign this issue I want to contribute on this issue.

**Comment by pallavi2031** [comment]
genuine sorry by mistake I did create PR without assign the issue.

**Comment by bosedipayan** [comment]
> genuine sorry by mistake I did create PR without assign the issue.

Please close it and create your own issue

**Comment by pallavi2031** [comment]
ok
